### ISSUE TITLE
Add onLoad props in react version

### ISSUE THREAD

**Issue by black80** [Tap-Payments/goSell-JSLib-Documentation#10]
I did read your documentation carefully and i noticed that there's isn't anything tells me that your checkout component is loaded because i did face an issue when i try to call your component and it only shows loading indicator then i noticed that you console a value (hey loaded) whenever the component is ready 
![Tap](https://user-images.githubusercontent.com/31955679/94340651-32fd4a00-000c-11eb-9e62-8cf79871e896.png)
FYI i modified your code but in a bad way to solve this issue

**Comment by halaq** [comment]
Hi @black80 

Thanks for reporting this issue, which version are you using please?

**Comment by Abdelhadi92** [comment]
Hi @halaq 
I used 1.6.0 version and the issue still not fixed.
