### ISSUE TITLE
MarketPlace Key

### ISSUE THREAD

**Issue by mansourSaleh** [Tap-Payments/goSell-JSLib-Documentation#11]
Hello,
Hope you are doing well,
I am trying to integrate with your payment.
I want to create a marketplace and create businesses in my marketplace.
your docs are very useful, yet I can not obtain the Marketplace Keys.
I asked the support team in the chat for these keys and they refer me to the documentation page.
In the documentation:

> You have to request for a test marketplace account to Tap. Tap will create a Marketplace account for your business and share two sets of credentials. One for creating businesses, and another for performing transactions.

Am I missing something or doing something wrong?
When I try to add a new business with my Keys that in Tab dashboard. it response with 401 
`{
    "status": "fail",
    "type": "api_key_not_authorized",
    "message": "Api key is unauthorized to perform the operation"
}`
Thanks.
How can I create a Marketplace account?

**Comment by tkdonny** [comment]
Hello Mansour. 
Thanks for contacting us.
Your marketplace account is being activated. 
We will share the credentials via email.

Regards,
Donny

**Comment by halaq** [comment]
Thank you @tkdonny 
@mansourSaleh The team has been contacted you by email and they activated your account. 
I hope you enjoy tap payments services. 👍🏻 

do you need anything else?
