### ISSUE TITLE
Can we do subscriptions ( monthly reoccurring payments ) using this goSell Lib.

### ISSUE THREAD

**Issue by jagroop** [Tap-Payments/goSell-JSLib-Documentation#5]
Can we do subscriptions ( monthly reoccurring payments ) using this goSell Lib.
After reading the Readme i see there is only one time charge option
can we do subscriptions also , If yes how ?
Thanks :)

**Comment by jagroop** [comment]
Yes i have tried reaching support team , its been 3 weeks they were not able to help :|

**Comment by halaq** [comment]
Hi @jagroop 

Sorry for the delay, for next time please contact our technical support on the chat in https://www.tap.company website. 

About your question, we don't have subscriptions in the checkout library but I will deliver your request to the company.

currently you can use tap APIs instead, you can find the documentation in the following link: https://www.tap.company/kw/en/developers
