### ISSUE TITLE
How to setup Apple Pay for web? 

### ISSUE THREAD

**Issue by shaktijs** [Tap-Payments/goSell-JSLib-Documentation#6]
Hi,

I need some help on "Apple Pay" integration for the website payment page. I've tried `supportedPaymentMethods = ["Apple Pay"]`  or "all" but it does not show the Apple pay button. 
I've tested on iPhone 6s safari browser from India. Here is demo code I'm following 

`
<html>
<head>
    <title>goSell Demo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <link rel="shortcut icon" href="https://goSellJSLib.b-cdn.net/v1.4.1/imgs/tap-favicon.ico" />
    <link href="https://goSellJSLib.b-cdn.net/v1.4.1/css/gosell.css" rel="stylesheet" />
</head>
<body>
    <script type="text/javascript" src="https://goSellJSLib.b-cdn.net/v1.4.1/js/gosell.js"></script>

    <div id="root"></div>
    <button id="openLightBox" onclick="goSell.openLightBox()">open goSell LightBox</button>
    <button id="openPage" onclick="goSell.openPaymentPage()">open goSell Page</button>

    <script>

    goSell.config({
      containerID:"root",
      gateway:{
        publicKey:"pk_test_Vlk842B1EA7tDN5QbrfGjYzh",
        language:"en",
        contactInfo:true,
        supportedCurrencies:"all",
        supportedPaymentMethods: "all",
        saveCardOption:false,
        customerCards: true,
        notifications:'standard',
        callback:(response) => {
            console.log('response', response);
        },
        onClose: () => {
            console.log("onClose Event");
        },
        labels:{
            cardNumber:"Card Number",
            expirationDate:"MM/YY",
            cvv:"CVV",
            cardHolder:"Name on Card",
            actionButton:"Pay"
        }
      },
     transaction:{
       mode: 'token'
     }
    });

    </script>

</body>
</html>
`

**Comment by halaq** [comment]
Hi @shaktijs 

Apple Pay is not working by token mode, it's available with charge mode only. 
if you modify the above configurations, you will be able to use Apple pay with Safari browser and goSell.openPaymentPage() function.  

If you have any further questions, please contact our technical support in intercom from our website: https://www.tap.company
