### ISSUE TITLE
goSell + TypeScript (TSX) 2119 error code

### ISSUE THREAD

**Issue by y-albaiz** [Tap-Payments/goSell-JSLib-Documentation#7]
Hi,

Im using the gosell lib by including the script tag in the html file but I cannot call `goSell.config` or any other goSell functions within the typescript application because they are not defined there.

I tried to work through this by defining a window function 
```
window.goSellConfig = function(config) {
      goSell.config(config);
};
```
and the same with the lightbox function and they seem to fire but the `generate` api request body has an empty `customer` object even when it is not empty. (I console.log it before calling goSell.config).

I get this response from the `config-log` api call:
```
{
   "status":200,
   "message":{
      "public_key":"pk_test_Zt5PqCwbBRsAIJcHXLE84UVh",
      "error_code":"2119",
      "error_msg":"Something went wrong! Please check the customer details",
      ...
      ...
      "backend_session_token":"5f3aa2ae01896800d4116a53",
      "created_at":"2020-08-17T15:30:56.301Z",
      "time_zone":"8/17/2020, 6:30:56 PM",
      ...
   }
}
```

What's confusing is two things:
- The fact that the customer object is not empty but gets sent as empty.
- `"error_code":"2119"` which is not preset [here](https://www.tap.company/sa/en/developers) under Response Codes --> Error Codes.

**Comment by y-albaiz** [comment]
Cc: @halaq

**Comment by halaq** [comment]
Hi @y-albaiz 

I need some details to help, can you share your code or answer on the following questions: 

First, are you using vanilla JS or one of its frameworks? 

Second, where are you including the script tag in HTML file exactly? in <head> or <body> tag? 

Third, are you calling goSell.config(config); on page load? 

Forth, from where you're getting the customer details? I guess there's a delay between generating the customer details and config function.

**Comment by y-albaiz** [comment]
Hi @halaq 
1st: I am using VueJS + Typescript.
2nd: In the `<head>` of the HTML file.
3rd: No, We're calling it once we fetch the configs from our api because we are working on a SPA and pages are rendered on the browser.
4th: From our api using an axios call.

I thought it was a delay at first but this is how we implemented it:
in `app.blade.php` (Our HTML file)
```
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        @yield('top_js')
        <link href="https://goSellJSLib.b-cdn.net/v1.4.1/css/gosell.css" rel="stylesheet" />
        <script type="text/javascript" src="https://goSellJSLib.b-cdn.net/v1.4.1/js/gosell.js"></script>
        <script type="text/javascript">
            window.goSellConfig = function (config) {
                goSell.config(config);
            }
            window.goSellOpenLightBox = function () {
                goSell.openLightBox();
            }
            var __INITIAL_STATE__ = {
              // Pass user data to the application initial state
              user: {!! json_encode($user) !!},
              appLocale: '{!! app()->getLocale() ?? "ar" !!}'
            };
        </script>
    </head>
```
in `window.d.ts` (Type definition for the `window` object so our ts spa can recognise it)
```
declare global {
  interface Window {
    __INITIAL_STATE__: {
      user: ApiModelUserInterface;
      appLocale: string;
    };
    goSellConfig: Function;
    goSellOpenLightBox: Function;
  }
}
```
And in our Vue component (e.g. `Component.tsx`) we call `window.goSellConfig()` and pass the configs after they are fetched from our api.

Again, the function `window.goSellConfig` fires correctly and I even `console.log`'d the configs object and it was correct but the `generate` api call from the gosell lib gets sent with an empty `customer` object.

**Comment by halaq** [comment]
Hi @y-albaiz 
Sorry for the delay. 

The only reasons that come to my mind are: 
1. Adding the script tags in <head> instead of <body> tag which's not a good practice.
2. Having some delays between calling the `generate` API and your config API. 

can you check the above and update me please?

**Comment by y-albaiz** [comment]
Hi Hala,
Thanks for the response.
I'll go with a more orthodox approach and update you.

**Comment by halaq** [comment]
Good luck @y-albaiz
