### ISSUE TITLE
order.taxes Object Structure

### ISSUE THREAD

**Issue by abdrhmn** [Tap-Payments/goSell-JSLib-Documentation#9]
Hello @halaq 

There is no definition or example of the `order.taxes` object.
Can you please explain it with an example?

**Comment by halaq** [comment]
Hi @abdrhmn 

I just noticed your question, sorry for the delay. 
`order.taxes` is not supported yet, it has been added to the library for future needs.

**Comment by yamenarahman** [comment]
@halaq Hello there, how about `order.shipping` ?

**Comment by yamenarahman** [comment]
@halaq I tried to use shipping as a string as mentioned in the readme but it shows this error:
<img width="1139" alt="Screen Shot 2020-11-12 at 11 36 19 AM" src="https://user-images.githubusercontent.com/24607365/98924095-227e3180-24dd-11eb-9f35-22c04dffb5b4.png">

I thought it needs to be an array, when I placed it as an array, the error is gone the shipping value is not shown in the popup.

<img width="849" alt="Screen Shot 2020-11-12 at 11 35 10 AM" src="https://user-images.githubusercontent.com/24607365/98924261-4d688580-24dd-11eb-8b76-e1df3c097a64.png">

<img width="545" alt="Screen Shot 2020-11-12 at 11 33 58 AM" src="https://user-images.githubusercontent.com/24607365/98924314-578a8400-24dd-11eb-9709-8f2d3f214ae8.png">

**Comment by halaq** [comment]
Hi @yamenarahman 

`order. shipping` same as `order.taxes`. it's not supported yet, it has been added to the library for future needs. 
The current version supports `amount`, `currency` and `items` only.

**Comment by yamenarahman** [comment]
Thanks for quick response.

**Comment by halaq** [comment]
You're welcome
